### PR TITLE
Fix utf8 issue

### PR DESCRIPTION
**Pull request by spacepope**
Hi Chris,

i found the cause of https://github.com/litehelpers/Android-sqlite-evcore-native-driver-free/issues/1.

As sqlite3_column_text() returns an unsigned char*, checking each byte as signed int could result in misinterpreted bitmask and therefore malformatted unicode signs.
Getting each byte into an unsigned char instead of an int seems to fix this issue. 🎉 

Can you please confirm this and merge the fix or the fixed libraries also in your https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free repository?

(i had to modify the jni/*.mk files to be able to successfully compile and use this library under Windows 10 bash. Not sure if you need this, but i included it in the PR anyway..)

Thanks and best regards,

Hannes

### CODE REVIEW

**Comment by spacepope** [comment]
Also as a sidenote to this:

cutting out all chars below 32 could be problematic too sometimes (look at ```} else if (pc >= 32 && pc < 127) {```).

One should be able to get the complete UTF-8 string out of SQLite as it is stored, regardless of code entry point values in it.. 
(perhaps something like decribed at http://shakddoo.github.io/ndk-unicode-utf8/ ?)

**Comment by brody2consult** [comment]
Thanks for the contribution, please accept my apologies for the delay in integrating this one as well as <https://github.com/litehelpers/Cordova-sqlite-storage/pull/709>.

I just saw the issue in case of 2-octet and 3-octet UTF-8 characters on Android x86_64 emulator, hoping to make this fix in the near future for which you will absolutely get credit.

> cutting out all chars below 32 could be problematic too sometimes (look at `} else if (pc >= 32 && pc < 127) {`).

Sounds right, will test further to be absolutely sure.

_P.S. Also reproduced on x86 (32-bit) emulator_

**Comment by spacepope** [comment]
Nice!
If something can be reproduced, it can be fixed/enhanced... 👍 
Definitely looking forward to see this getting more "bullet proof" 😃

**Comment by brody2consult** [comment]
The issue you reported in #1 is now resolved, solution is very similar to what @spacepope proposed here to resolve a conversion warning (a second, similar warning was also resolved for x86 & x86_64).

The issue with character values below 32 will be handled in <https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free/issues/28>, should be resolved in the near future.

My apologies to anyone who may have been affected by the delay.

**Pull request closed without merging**
